# Site settings
author: Becky Phan
title: Ode to Code
header-img: img/home-bg.png
email: beckyphan@live.com
copyright_name: Becky Phan
description: > # this means to ignore newlines until "baseurl:"
  a technical blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  beckyphan

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
